package org.apache.ambari.server.controller.internal;
import static org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION;
import static org.apache.ambari.server.configuration.AmbariServerConfigurationKey.BIND_PASSWORD;
import static org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS;
import static org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED;
import static org.apache.ambari.server.configuration.ConfigurationPropertyType.PASSWORD;
import static org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN;
public class AmbariServerConfigurationUtilsTest {
    @org.junit.Test
    public void testGetConfigurationKey() {
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationCategory(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationCategory().getCategoryName(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "ambari.tproxy.proxyuser.knox.groups"));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "ambari.tproxy.proxyuser.not.knox.groups"));
        org.junit.Assert.assertNull(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "invalid.tproxy.proxyuser.not.knox.groups"));
        org.junit.Assert.assertNull(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(((org.apache.ambari.server.configuration.AmbariServerConfigurationCategory) (null)), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertNull(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(((java.lang.String) (null)), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertNull(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey("invalid", org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertNull(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION.getCategoryName(), null));
        org.junit.Assert.assertNull(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationKey(org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION.getCategoryName(), "invalid"));
    }

    @org.junit.Test
    public void testGetConfigurationPropertyType() {
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationPropertyType(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationCategory(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationPropertyType(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationCategory().getCategoryName(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "ambari.tproxy.proxyuser.knox.groups"));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "ambari.tproxy.proxyuser.not.knox.groups"));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "invalid.tproxy.proxyuser.not.knox.groups"));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(((org.apache.ambari.server.configuration.AmbariServerConfigurationCategory) (null)), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(((java.lang.String) (null)), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType("invalid", org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION.getCategoryName(), null));
        org.junit.Assert.assertSame(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyType(org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION.getCategoryName(), "invalid"));
    }

    @org.junit.Test
    public void testGetConfigurationPropertyTypeName() {
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationPropertyType().name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationCategory(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationPropertyType().name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationCategory().getCategoryName(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType().name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType().name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "ambari.tproxy.proxyuser.knox.groups"));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType().name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "ambari.tproxy.proxyuser.not.knox.groups"));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN.name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "invalid.tproxy.proxyuser.not.knox.groups"));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN.name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(((org.apache.ambari.server.configuration.AmbariServerConfigurationCategory) (null)), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN.name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(((java.lang.String) (null)), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN.name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName("invalid", org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN.name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION.getCategoryName(), null));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.ConfigurationPropertyType.UNKNOWN.name(), org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.getConfigurationPropertyTypeName(org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION.getCategoryName(), "invalid"));
    }

    @org.junit.Test
    public void isPassword() {
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationPropertyType() == org.apache.ambari.server.configuration.ConfigurationPropertyType.PASSWORD, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationCategory(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationPropertyType() == org.apache.ambari.server.configuration.ConfigurationPropertyType.PASSWORD, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.getConfigurationCategory().getCategoryName(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType() == org.apache.ambari.server.configuration.ConfigurationPropertyType.PASSWORD, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.key()));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType() == org.apache.ambari.server.configuration.ConfigurationPropertyType.PASSWORD, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "ambari.tproxy.proxyuser.knox.groups"));
        org.junit.Assert.assertEquals(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationPropertyType() == org.apache.ambari.server.configuration.ConfigurationPropertyType.PASSWORD, org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "ambari.tproxy.proxyuser.not.knox.groups"));
        org.junit.Assert.assertFalse(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_ALLOWED_GROUPS.getConfigurationCategory().getCategoryName(), "invalid.tproxy.proxyuser.not.knox.groups"));
        org.junit.Assert.assertFalse(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(((org.apache.ambari.server.configuration.AmbariServerConfigurationCategory) (null)), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertFalse(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(((java.lang.String) (null)), org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertFalse(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword("invalid", org.apache.ambari.server.configuration.AmbariServerConfigurationKey.TPROXY_AUTHENTICATION_ENABLED.key()));
        org.junit.Assert.assertFalse(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION.getCategoryName(), null));
        org.junit.Assert.assertFalse(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationCategory.TPROXY_CONFIGURATION.getCategoryName(), "invalid"));
        org.junit.Assert.assertTrue(org.apache.ambari.server.controller.internal.AmbariServerConfigurationUtils.isPassword(org.apache.ambari.server.configuration.AmbariServerConfigurationKey.BIND_PASSWORD));
    }
}